const createdAt = '2024-01-01T00:00:00Z';

export const demoOrganizations = [
  {
    id: 'acme-sales-org',
    name: 'Acme Sales Org',
    planTier: 'pro',
    createdAt,
  },
  {
    id: 'viewer-org',
    name: 'Viewer Test Org',
    planTier: 'basic',
    createdAt,
  },
];

export const demoUsers = [
  {
    id: 'user-1',
    email: 'demo@mudul.com',
    name: 'Demo User',
    createdAt,
    lastLoginAt: '2024-01-15T10:00:00Z',
  },
  {
    id: 'user-2',
    email: 'viewer@mudul.com',
    name: 'Viewer User',
    createdAt,
    lastLoginAt: '2024-01-15T10:00:00Z',
  },
];

export const demoMemberships = [
  {
    id: 'mem-1',
    userId: 'user-1',
    orgId: 'acme-sales-org',
    role: 'owner',
    createdAt,
  },
  {
    id: 'mem-2',
    userId: 'user-2',
    orgId: 'viewer-org',
    role: 'viewer',
    createdAt,
  },
];

export const demoClients = [
  {
    id: 'client-acme',
    orgId: 'acme-sales-org',
    name: 'Acme Corp',
    slug: 'acme-corp',
    createdAt,
  },
  {
    id: 'client-beta',
    orgId: 'acme-sales-org',
    name: 'Beta Systems',
    slug: 'beta-systems',
    createdAt,
  },
  {
    id: 'client-gamma',
    orgId: 'acme-sales-org',
    name: 'Gamma Industries',
    slug: 'gamma-industries',
    createdAt,
  },
  {
    id: 'client-viewer-test',
    orgId: 'viewer-org',
    name: 'Viewer Test Client',
    slug: 'viewer-test-client',
    createdAt,
  },
];

export const demoCalls = [
  {
    id: 'call-acme-1',
    orgId: 'acme-sales-org',
    clientId: 'client-acme',
    name: 'Discovery Call - Jan 15',
    slug: 'discovery-jan-15',
    sessionId: 'session-acme-1',
    summary: "Great discovery call with Acme Corp. They're interested in our enterprise solution to solve their scaling challenges.",
    ts: '2024-01-15T10:00:00Z',
    durationSec: 1800,
    sentiment: 'positive',
    score: 0.8,
    bookingLikelihood: 0.75,
    objections: [
      { type: 'budget', quote: 'Need to discuss budget with CFO', ts: '00:15:30' },
    ],
    keyMoments: [
      { label: 'pain point identified', ts: '00:05:45' },
      { label: 'budget discussion', ts: '00:15:30' },
    ],
    entities: {
      prospect: ['Acme Corp'],
      people: ['John Smith', 'Sarah Johnson'],
      products: ['Enterprise Plan'],
    },
    complianceFlags: [],
  },
  {
    id: 'call-acme-2',
    orgId: 'acme-sales-org',
    clientId: 'client-acme',
    name: 'Follow-up Call - Jan 20',
    slug: 'followup-jan-20',
    sessionId: 'session-acme-2',
    summary: 'Follow-up call went well. Acme Corp is ready to move forward with pilot program.',
    ts: '2024-01-20T14:00:00Z',
    durationSec: 1200,
    sentiment: 'positive',
    score: 0.9,
    bookingLikelihood: 0.9,
    objections: [],
    keyMoments: [
      { label: 'pilot agreement', ts: '00:08:15' },
      { label: 'timeline discussion', ts: '00:12:00' },
    ],
    entities: {
      prospect: ['Acme Corp'],
      people: ['John Smith', 'Michael Davis'],
      products: ['Enterprise Plan', 'Professional Services'],
    },
    complianceFlags: [],
  },
  {
    id: 'call-beta-1',
    orgId: 'acme-sales-org',
    clientId: 'client-beta',
    name: 'Initial Contact - Jan 12',
    slug: 'initial-jan-12',
    sessionId: 'session-beta-1',
    summary: 'Initial contact with Beta Systems. They have budget constraints but are interested in our basic offering.',
    ts: '2024-01-12T09:00:00Z',
    durationSec: 2100,
    sentiment: 'neutral',
    score: 0.6,
    bookingLikelihood: 0.4,
    objections: [
      { type: 'budget', quote: 'Our budget is quite limited this quarter', ts: '00:10:15' },
      { type: 'timing', quote: 'Might need to wait until Q2', ts: '00:18:45' },
    ],
    keyMoments: [
      { label: 'budget concerns', ts: '00:10:15' },
      { label: 'Q2 timeline', ts: '00:18:45' },
    ],
    entities: {
      prospect: ['Beta Systems'],
      people: ['Lisa Wong', 'David Kim'],
      products: ['Basic Plan'],
    },
    complianceFlags: [],
  },
  {
    id: 'call-beta-2',
    orgId: 'acme-sales-org',
    clientId: 'client-beta',
    name: 'Demo Call - Jan 18',
    slug: 'demo-jan-18',
    sessionId: 'session-beta-2',
    summary: 'Demo went very well! Beta Systems loved the user interface and core features.',
    ts: '2024-01-18T16:00:00Z',
    durationSec: 2700,
    sentiment: 'positive',
    score: 0.85,
    bookingLikelihood: 0.7,
    objections: [
      { type: 'integration', quote: 'Need to ensure it works with our existing systems', ts: '00:22:30' },
    ],
    keyMoments: [
      { label: 'demo highlight', ts: '00:08:00' },
      { label: 'integration questions', ts: '00:22:30' },
    ],
    entities: {
      prospect: ['Beta Systems'],
      people: ['Lisa Wong', 'Robert Chen'],
      products: ['Basic Plan', 'API Integration'],
    },
    complianceFlags: [],
  },
  {
    id: 'call-gamma-1',
    orgId: 'acme-sales-org',
    clientId: 'client-gamma',
    name: 'Qualification Call - Jan 22',
    slug: 'qualification-jan-22',
    sessionId: 'session-gamma-1',
    summary: 'Qualification call with Gamma Industries. Large enterprise with complex needs.',
    ts: '2024-01-22T11:00:00Z',
    durationSec: 3000,
    sentiment: 'neutral',
    score: 0.55,
    bookingLikelihood: 0.5,
    objections: [
      { type: 'complexity', quote: 'Our requirements are quite complex', ts: '00:12:00' },
      { type: 'decision_making', quote: 'Multiple stakeholders need to be involved', ts: '00:20:15' },
    ],
    keyMoments: [
      { label: 'requirements discussion', ts: '00:12:00' },
      { label: 'stakeholder identification', ts: '00:20:15' },
    ],
    entities: {
      prospect: ['Gamma Industries'],
      people: ['Amanda Rodriguez', 'Thomas Wilson', 'Jennifer Lee'],
      products: ['Enterprise Plan', 'Custom Integration'],
    },
    complianceFlags: ['multi-stakeholder-approval'],
  },
  {
    id: 'call-viewer-1',
    orgId: 'viewer-org',
    clientId: 'client-viewer-test',
    name: 'Viewer Org Call',
    slug: 'viewer-org-call',
    sessionId: 'session-viewer-1',
    summary: 'Test call for viewer organization.',
    ts: '2024-01-10T12:00:00Z',
    durationSec: 1500,
    sentiment: 'positive',
    score: 0.75,
    bookingLikelihood: 0.8,
    objections: [],
    keyMoments: [
      { label: 'intro complete', ts: '00:03:00' },
    ],
    entities: {
      prospect: ['Viewer Test Client'],
      people: ['Viewer User'],
      products: ['Basic Plan'],
    },
    complianceFlags: [],
  },
];

export const demoActionItems = [
  {
    id: 'action-1',
    orgId: 'acme-sales-org',
    clientId: 'client-acme',
    callId: 'call-acme-1',
    owner: 'rep',
    ownerId: 'user-1',
    text: 'Send enterprise pricing proposal',
    due: '2024-01-18',
    status: 'open',
  },
  {
    id: 'action-2',
    orgId: 'acme-sales-org',
    clientId: 'client-acme',
    callId: 'call-acme-1',
    owner: 'prospect',
    ownerId: null,
    text: 'Review with technical team',
    due: '2024-01-17',
    status: 'open',
  },
  {
    id: 'action-3',
    orgId: 'acme-sales-org',
    clientId: 'client-acme',
    callId: 'call-acme-2',
    owner: 'rep',
    ownerId: 'user-1',
    text: 'Prepare pilot program proposal',
    due: '2024-01-25',
    status: 'open',
  },
  {
    id: 'action-4',
    orgId: 'acme-sales-org',
    clientId: 'client-acme',
    callId: 'call-acme-2',
    owner: 'rep',
    ownerId: 'user-1',
    text: 'Schedule technical onboarding',
    due: null,
    status: 'open',
  },
  {
    id: 'action-5',
    orgId: 'acme-sales-org',
    clientId: 'client-beta',
    callId: 'call-beta-1',
    owner: 'rep',
    ownerId: 'user-1',
    text: 'Send basic plan pricing',
    due: '2024-01-15',
    status: 'open',
  },
  {
    id: 'action-6',
    orgId: 'acme-sales-org',
    clientId: 'client-beta',
    callId: 'call-beta-1',
    owner: 'prospect',
    ownerId: null,
    text: 'Discuss with procurement',
    due: '2024-01-20',
    status: 'open',
  },
  {
    id: 'action-7',
    orgId: 'acme-sales-org',
    clientId: 'client-beta',
    callId: 'call-beta-2',
    owner: 'rep',
    ownerId: 'user-1',
    text: 'Provide integration documentation',
    due: '2024-01-22',
    status: 'open',
  },
  {
    id: 'action-8',
    orgId: 'acme-sales-org',
    clientId: 'client-beta',
    callId: 'call-beta-2',
    owner: 'rep',
    ownerId: 'user-1',
    text: 'Schedule technical Q&A session',
    due: '2024-01-25',
    status: 'open',
  },
  {
    id: 'action-9',
    orgId: 'acme-sales-org',
    clientId: 'client-gamma',
    callId: 'call-gamma-1',
    owner: 'rep',
    ownerId: 'user-1',
    text: 'Schedule stakeholder presentation',
    due: '2024-01-30',
    status: 'open',
  },
  {
    id: 'action-10',
    orgId: 'acme-sales-org',
    clientId: 'client-gamma',
    callId: 'call-gamma-1',
    owner: 'prospect',
    ownerId: null,
    text: 'Compile detailed requirements',
    due: '2024-01-28',
    status: 'open',
  },
];